spring:
  datasource:
    url: jdbc:mysql://10.203.15.100:3306/bbg_plat_member?useUnicode=true&characterEncoding=utf-8
    username: slave_yun
    password: slave_yun_prd
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid